"""Synthetic but geographically plausible renewable asset catalogue."""

from __future__ import annotations

from typing import TypedDict


class Asset(TypedDict):
    asset_id: str
    code: str
    name: str
    technology: str
    region: str
    municipality: str
    latitude: float
    longitude: float
    capacity_mw: float
    commissioning_date: str
    status: str
    manufacturer: str
    model: str
    portfolio: str
    expected_availability: float


ASSETS: list[Asset] = [
    {
        "asset_id": "sol-cmn-01",
        "code": "LUM-01",
        "name": "Lumen La Mancha",
        "technology": "solar",
        "region": "Castilla-La Mancha",
        "municipality": "Alcázar",
        "latitude": 39.39,
        "longitude": -3.21,
        "capacity_mw": 62.0,
        "commissioning_date": "2019-05-14",
        "status": "online",
        "manufacturer": "Ficta Solar",
        "model": "FS-MONO-540",
        "portfolio": "Iberia Core",
        "expected_availability": 0.985,
    },
    {
        "asset_id": "sol-ext-02",
        "code": "ENC-02",
        "name": "Encina Solar",
        "technology": "solar",
        "region": "Extremadura",
        "municipality": "Trujillo",
        "latitude": 39.46,
        "longitude": -5.88,
        "capacity_mw": 48.0,
        "commissioning_date": "2020-09-22",
        "status": "attention",
        "manufacturer": "Ficta Solar",
        "model": "FS-MONO-540",
        "portfolio": "Iberia Core",
        "expected_availability": 0.982,
    },
    {
        "asset_id": "sol-and-03",
        "code": "SIE-03",
        "name": "Sierra Clara",
        "technology": "solar",
        "region": "Andalucía",
        "municipality": "Écija",
        "latitude": 37.55,
        "longitude": -5.12,
        "capacity_mw": 72.0,
        "commissioning_date": "2021-03-18",
        "status": "online",
        "manufacturer": "Helios Systems",
        "model": "HS-BIFACIAL-610",
        "portfolio": "Iberia Core",
        "expected_availability": 0.988,
    },
    {
        "asset_id": "sol-ara-04",
        "code": "MON-04",
        "name": "Moncayo Luz",
        "technology": "solar",
        "region": "Aragón",
        "municipality": "Borja",
        "latitude": 41.82,
        "longitude": -1.54,
        "capacity_mw": 38.0,
        "commissioning_date": "2018-11-08",
        "status": "online",
        "manufacturer": "Helios Systems",
        "model": "HS-PERC-485",
        "portfolio": "Iberia Flex",
        "expected_availability": 0.979,
    },
    {
        "asset_id": "sol-nav-05",
        "code": "RIB-05",
        "name": "Ribera Solar",
        "technology": "solar",
        "region": "Navarra",
        "municipality": "Tudela",
        "latitude": 42.06,
        "longitude": -1.60,
        "capacity_mw": 44.0,
        "commissioning_date": "2022-06-02",
        "status": "online",
        "manufacturer": "Ficta Solar",
        "model": "FS-MONO-540",
        "portfolio": "Iberia Flex",
        "expected_availability": 0.991,
    },
    {
        "asset_id": "wnd-gal-01",
        "code": "ATL-11",
        "name": "Atlántico Norte",
        "technology": "wind",
        "region": "Galicia",
        "municipality": "Muras",
        "latitude": 43.47,
        "longitude": -7.72,
        "capacity_mw": 80.0,
        "commissioning_date": "2017-04-27",
        "status": "online",
        "manufacturer": "Aether Wind",
        "model": "AW-4.0",
        "portfolio": "Iberia Core",
        "expected_availability": 0.972,
    },
    {
        "asset_id": "wnd-cyl-02",
        "code": "PAR-12",
        "name": "Páramo Alto",
        "technology": "wind",
        "region": "Castilla y León",
        "municipality": "Medina",
        "latitude": 41.33,
        "longitude": -4.91,
        "capacity_mw": 64.0,
        "commissioning_date": "2019-08-12",
        "status": "online",
        "manufacturer": "Aether Wind",
        "model": "AW-3.2",
        "portfolio": "Iberia Core",
        "expected_availability": 0.976,
    },
    {
        "asset_id": "wnd-ara-03",
        "code": "CIE-13",
        "name": "Cierzo Este",
        "technology": "wind",
        "region": "Aragón",
        "municipality": "Belchite",
        "latitude": 41.30,
        "longitude": -0.75,
        "capacity_mw": 92.0,
        "commissioning_date": "2020-12-17",
        "status": "attention",
        "manufacturer": "Mistral Dynamics",
        "model": "MD-4.6",
        "portfolio": "Iberia Flex",
        "expected_availability": 0.981,
    },
    {
        "asset_id": "wnd-nav-04",
        "code": "BAL-14",
        "name": "Balsa Verde",
        "technology": "wind",
        "region": "Navarra",
        "municipality": "Olite",
        "latitude": 42.48,
        "longitude": -1.66,
        "capacity_mw": 56.0,
        "commissioning_date": "2018-02-09",
        "status": "online",
        "manufacturer": "Aether Wind",
        "model": "AW-3.2",
        "portfolio": "Iberia Flex",
        "expected_availability": 0.974,
    },
    {
        "asset_id": "wnd-and-05",
        "code": "LEV-15",
        "name": "Levante Sur",
        "technology": "wind",
        "region": "Andalucía",
        "municipality": "Tarifa",
        "latitude": 36.11,
        "longitude": -5.55,
        "capacity_mw": 70.0,
        "commissioning_date": "2021-10-21",
        "status": "online",
        "manufacturer": "Mistral Dynamics",
        "model": "MD-3.5",
        "portfolio": "Iberia Core",
        "expected_availability": 0.984,
    },
    {
        "asset_id": "bat-cmn-01",
        "code": "RES-21",
        "name": "Reserva Central",
        "technology": "battery",
        "region": "Castilla-La Mancha",
        "municipality": "Alcázar",
        "latitude": 39.42,
        "longitude": -3.14,
        "capacity_mw": 20.0,
        "commissioning_date": "2024-01-16",
        "status": "standby",
        "manufacturer": "Volt Reserve",
        "model": "VR-40MWh",
        "portfolio": "Iberia Flex",
        "expected_availability": 0.994,
    },
    {
        "asset_id": "bat-ara-02",
        "code": "PUL-22",
        "name": "Pulso Aragón",
        "technology": "battery",
        "region": "Aragón",
        "municipality": "Belchite",
        "latitude": 41.34,
        "longitude": -0.69,
        "capacity_mw": 24.0,
        "commissioning_date": "2024-09-05",
        "status": "online",
        "manufacturer": "Volt Reserve",
        "model": "VR-48MWh",
        "portfolio": "Iberia Flex",
        "expected_availability": 0.995,
    },
]


def asset_lookup() -> dict[str, Asset]:
    """Return a stable lookup keyed by public asset id."""

    return {asset["asset_id"]: asset for asset in ASSETS}
